/**
 * `desktop` and `browser.launchArgs`
 * (docs/specs/SPEC-use-computer.md §5.10; acceptance §13.1 "config defaults
 * and schema", §13 item 7).
 *
 * Note where the two halves of "validation" live. `loadConfig` has no
 * per-key type checking — it deep-merges a parsed JSON object over the
 * defaults, and has done since long before this section — so what it is
 * asserted to do here is MERGE correctly: a partial `desktop` block inherits
 * its sibling defaults, and an absent one leaves `enabled` false. Type
 * rejection is the generated JSON schema's job, in the editor, and the last
 * block tests it there. Asserting the loader threw on a string `settleMs`
 * would be asserting a behaviour that does not exist.
 */
import { describe, it, expect, afterAll, beforeAll } from 'vitest';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import Ajv from 'ajv';
import { DEFAULT_CONFIG } from '../src/config/defaults.js';
import { loadConfig } from '../src/config/loader.js';

const dirs: string[] = [];

function projectWith(config: Record<string, unknown>): string {
  const dir = mkdtempSync(path.join(tmpdir(), 'aiui-desktop-config-'));
  dirs.push(dir);
  writeFileSync(path.join(dir, 'aiui.config.json'), JSON.stringify(config, null, 2), 'utf8');
  return dir;
}

afterAll(() => {
  for (const dir of dirs) rmSync(dir, { recursive: true, force: true });
});

describe('DEFAULT_CONFIG.desktop — §5.10', () => {
  it('carries the four documented defaults', () => {
    expect(DEFAULT_CONFIG.desktop).toEqual({
      enabled: false,
      maxImageWidth: 1600,
      settleMs: 300,
      reportScreenshots: true,
    });
  });

  it('is OFF by default — a shared project must opt in (§5.1 item 1)', () => {
    expect(DEFAULT_CONFIG.desktop.enabled).toBe(false);
  });

  it('ships no launchArgs — the launcher\'s own flags are the whole list', () => {
    expect(DEFAULT_CONFIG.browser.launchArgs).toBeUndefined();
  });
});

describe('loadConfig — the new keys', () => {
  it('an unconfigured project gets the defaults', async () => {
    const dir = mkdtempSync(path.join(tmpdir(), 'aiui-desktop-none-'));
    dirs.push(dir);
    const config = await loadConfig(undefined, dir);
    expect(config.desktop).toEqual(DEFAULT_CONFIG.desktop);
  });

  it('reads an enabled desktop section', async () => {
    const config = await loadConfig(
      undefined,
      projectWith({ desktop: { enabled: true, maxImageWidth: 1280, settleMs: 500 } }),
    );
    expect(config.desktop).toEqual({
      enabled: true,
      maxImageWidth: 1280,
      settleMs: 500,
      // Not named in the file, so it keeps its default — the deep merge is
      // per key, not per section.
      reportScreenshots: true,
    });
  });

  it('keeps every other default when only one key is set', async () => {
    const config = await loadConfig(undefined, projectWith({ desktop: { reportScreenshots: false } }));
    expect(config.desktop).toEqual({
      enabled: false,
      maxImageWidth: 1600,
      settleMs: 300,
      reportScreenshots: false,
    });
  });

  it('reads browser.launchArgs, replacing rather than merging the array', async () => {
    const config = await loadConfig(
      undefined,
      projectWith({ browser: { launchArgs: ['--disable-print-preview'] } }),
    );
    expect(config.browser.launchArgs).toEqual(['--disable-print-preview']);
    // The sibling browser defaults survive.
    expect(config.browser.headed).toBe(true);
  });
});

describe('aiui.config.schema.json — desktop and browser.launchArgs', () => {
  // The schema is a committed artifact regenerated by `npm run build:schema`
  // (part of `npm run build`). These assertions fail if it was not re-run,
  // which is the only signal a reader gets that the editor's autocomplete and
  // the code have drifted apart.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let validate: any;

  beforeAll(async () => {
    const schemaText = await readFile(
      path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../schema/aiui.config.schema.json'),
      'utf8',
    );
    const ajv = new Ajv({ strict: false, allErrors: true });
    validate = ajv.compile(JSON.parse(schemaText));
  });

  it('accepts a full desktop section', () => {
    expect(
      validate({
        desktop: { enabled: true, maxImageWidth: 1600, settleMs: 300, reportScreenshots: false },
      }),
    ).toBe(true);
  });

  it('accepts a partial one', () => {
    expect(validate({ desktop: { enabled: true } })).toBe(true);
  });

  it.each([
    ['enabled as a string', { desktop: { enabled: 'yes' } }],
    ['maxImageWidth as a string', { desktop: { maxImageWidth: '1600' } }],
    ['settleMs as a string', { desktop: { settleMs: '300' } }],
    ['reportScreenshots as a number', { desktop: { reportScreenshots: 1 } }],
  ])('rejects %s', (_label, value) => {
    expect(validate(value)).toBe(false);
  });

  it('rejects a key that is not in the section', () => {
    // The generator emits `additionalProperties: false`, so a typo is caught
    // in the editor rather than silently ignored at run time.
    expect(validate({ desktop: { enable: true } })).toBe(false);
  });

  it('accepts browser.launchArgs as an array of strings', () => {
    expect(validate({ browser: { launchArgs: ['--disable-print-preview'] } })).toBe(true);
    expect(validate({ browser: { launchArgs: [] } })).toBe(true);
  });

  it('rejects a launchArgs that is one string rather than a list', () => {
    expect(validate({ browser: { launchArgs: '--disable-print-preview' } })).toBe(false);
    expect(validate({ browser: { launchArgs: [1, 2] } })).toBe(false);
  });

  it('documents each key, so the editor hover says what it does', () => {
    // The JSDoc → `description` path is the whole reason the schema is
    // generated from the types rather than written by hand.
    const raw = JSON.parse(
      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
      JSON.stringify(validate.schema),
    );
    const desktop = raw.definitions['DeepPartial<DesktopConfig>'];
    expect(desktop).toBeDefined();
    for (const key of ['enabled', 'maxImageWidth', 'settleMs', 'reportScreenshots']) {
      expect(desktop.properties[key].description, `${key} has no description`).toBeTruthy();
    }
  });
});
