/**
 * Tests for the `browser.video` config knob:
 *  - default 'off' (DEFAULT_CONFIG)
 *  - tri-state strings + boolean sugar pass through the loader's deepMerge
 *    unchanged (booleans are primitives → wholesale replace of the 'off' default)
 *  - the generated JSON schema accepts the three strings + true/false and
 *    rejects out-of-enum strings / non-boolean numbers (guards the schema
 *    generator emitting the `anyOf: [enum, boolean]` shape)
 *
 * Mirrors tests/config-loader.test.ts (loader + Ajv schema blocks). The schema
 * file is a committed artifact regenerated by `npm run build:schema` (part of
 * `npm run build`); these schema assertions require it to carry the new key.
 */
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import Ajv from 'ajv';
import { loadConfig } from '../src/config/loader.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

describe('browser.video — loader tri-state + boolean sugar', () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'aiui-video-'));
  });

  afterEach(async () => {
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  async function writeConfig(obj: unknown): Promise<string> {
    const file = path.join(tmpDir, 'aiui.config.json');
    await fs.writeFile(file, JSON.stringify(obj), 'utf8');
    return file;
  }

  it("defaults to 'off' when unspecified", async () => {
    const config = await loadConfig();
    expect(config.browser.video).toBe('off');
  });

  it("preserves 'retain-on-failure' and keeps sibling browser defaults", async () => {
    const file = await writeConfig({ browser: { video: 'retain-on-failure' } });
    const config = await loadConfig(file);
    expect(config.browser.video).toBe('retain-on-failure');
    // deepMerge keeps the other browser defaults rather than dropping them.
    expect(config.browser.headed).toBe(true);
  });

  it('passes boolean true through unchanged (replaces the off default)', async () => {
    const file = await writeConfig({ browser: { video: true } });
    const config = await loadConfig(file);
    expect(config.browser.video).toBe(true);
  });

  it('passes boolean false through unchanged', async () => {
    const file = await writeConfig({ browser: { video: false } });
    const config = await loadConfig(file);
    expect(config.browser.video).toBe(false);
  });
});

describe('aiui.config.schema.json — browser.video enum|boolean', () => {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let validate: any;

  beforeEach(async () => {
    const schemaText = await fs.readFile(
      path.resolve(__dirname, '../schema/aiui.config.schema.json'),
      'utf8',
    );
    const ajv = new Ajv({ strict: false, allErrors: true });
    validate = ajv.compile(JSON.parse(schemaText));
  });

  it('accepts the three canonical string values', () => {
    expect(validate({ browser: { video: 'off' } })).toBe(true);
    expect(validate({ browser: { video: 'on' } })).toBe(true);
    expect(validate({ browser: { video: 'retain-on-failure' } })).toBe(true);
  });

  it('accepts boolean sugar true/false', () => {
    expect(validate({ browser: { video: true } })).toBe(true);
    expect(validate({ browser: { video: false } })).toBe(true);
  });

  it('rejects an out-of-enum string', () => {
    expect(validate({ browser: { video: 'always' } })).toBe(false);
  });

  it('rejects a number (not boolean | enum)', () => {
    expect(validate({ browser: { video: 1 } })).toBe(false);
  });
});
