import { basename } from 'node:path';
import type { AiClient } from '../ai/client.js';
import type { ChatMessage } from '../ai/types.js';
import {
  decodeDoubleEscapedNewlines,
  extractJson,
  findInlinedParameterValue,
} from '../ai/action-parser.js';
import type { Candidate } from './candidate.js';
import { describeGuardedName } from './generate.js';
import { listEntries, validateCodeBehindSource } from './writer.js';

/**
 * The compiler's review pass (stories/codebehind-compile.md, "Review").
 *
 * One model call over the *complete* candidate file, against a checklist.
 * The characteristic bug of this feature — a model freezing today's date as a
 * literal — produces code that passes on the day it is written, so replay
 * cannot catch it. Only a reader asking "should this have been computed?" can.
 */

export interface FileReviewInput {
  /** Basename of the markdown this code-behind belongs to, for orientation. */
  markdownName: string;
  /** The candidate file, complete. */
  file: string;
  /** The test's steps, in order, so the reviewer can see what each entry is for. */
  steps: string[];
}

export function buildFileReviewPrompt(input: FileReviewInput): ChatMessage {
  const stepBlock = input.steps.length === 0
    ? '(step list unavailable)'
    : input.steps.map((s, i) => `${i + 1}. ${s}`).join('\n');

  return {
    role: 'user',
    content: `Review a generated Playwright code-behind file before it is committed.

Each entry in the file replaces one natural-language test step. The file runs
with no model call, on every future run, possibly for years.

## The test's steps
${stepBlock}

## The file, as generated
\`\`\`ts
${input.file}
\`\`\`

## The checklist

1. **Dynamic values are computed at runtime, not frozen.** A date, a derived
   code, a formatted number the step describes as a computation must be worked
   out in the code. A literal that was correct on the day of generation and
   wrong the next day is the single worst defect this file can carry — look for
   it first.
2. **Parameters are read via \`step.getVar('name')\`**, never inlined as
   literals.
3. **Every entry ends with a post-condition** — a \`locator.waitFor()\` on what
   the step produced, or a \`step.expect(...)\` over a value read back from the
   page — so "did not throw" means "the step worked".
4. **Captures are written**: a step with \`[as: x]\` must call
   \`step.setVar('x', ...)\`.
5. **Stable selectors** (ids, \`data-testid\`, roles, labels) over positional
   or index-based ones.
6. **No imports** beyond the file's existing \`defineSteps\` import, and no
   \`page.waitForTimeout\` unless it is genuinely unavoidable.
7. Leave \`source\` strings and \`section\` fields **exactly** as they are —
   they are how entries bind to steps, and an edit silently unbinds one. Never
   remove an entry, and **never add one**: a step with no entry is one the
   compile chose not to generate for, or has no recording of, and code written
   for it without a recording is a guess. The set of entries you return must
   be exactly the set you were given.
8. **Upload paths go through \`step.filePath('…')\`** — never a bare string
   literal handed to \`setInputFiles\`/\`setFiles\`, and never an absolute path. A
   path in a step is relative to the test file's folder, and only
   \`step.filePath\` resolves it that way at replay time.
9. An \`ai: true\` entry is a decision, not an omission: leave it alone,
   comment included. Do not turn one into a \`run\` entry, however obvious the
   code looks — something already established that this step needs the model.

## What to return

The complete revised file — not a diff, not a fragment — as one JSON string
field (standard JSON string encoding):

{
  "file": "// Generated by ai-ui-automation …\\nimport { defineSteps } …"
}

If nothing needs changing, return the file unchanged. Respond with ONLY the
JSON object — no prose around it.`,
  };
}

/**
 * Pull the revised file out of the `{"file": "..."}` envelope.
 *
 * Same double-escape decoding as the entry envelope: a model that writes
 * `\\n` inside the string leaves literal backslash-n in code position, which
 * can only ever be a syntax error.
 */
export function parseFileRevision(rawResponse: string): string {
  let body: string | undefined;
  try {
    const parsed: unknown = JSON.parse(extractJson(rawResponse));
    if (typeof parsed === 'object' && parsed !== null) {
      const file = (parsed as Record<string, unknown>)['file'];
      if (typeof file === 'string' && file.trim()) body = decodeDoubleEscapedNewlines(file);
    }
  } catch {
    // Not JSON — fall through to the fence path below.
  }

  if (body === undefined) {
    const fenced = /```(?:ts|typescript)?\s*\n([\s\S]*?)```/i.exec(rawResponse);
    if (fenced?.[1]) body = fenced[1];
  }

  const text = body?.trim();
  if (!text) throw new Error('Review response carried no revised file');
  if (!/\bdefineSteps\s*\(/.test(text)) {
    throw new Error('Review response is not a code-behind file (no `defineSteps(` call)');
  }
  return text.endsWith('\n') ? text : `${text}\n`;
}

/** What a review pass needs to know about the compile it is reviewing. */
export interface ReviewCandidateInput {
  /** Basename of the markdown this code-behind belongs to, for orientation. */
  markdownName: string;
  /** The test's authored step texts, in order — what every `source` matches. */
  steps: string[];
  /**
   * Every value the revision must not inline: the resolved parameters and the
   * resolved environment references. Deliberately broad — a whole-file rewrite
   * can move a literal into any entry, so the check has to cover them all.
   */
  guarded: Array<{ name: string; value: string }>;
  aiClient: AiClient;
  signal?: AbortSignal | undefined;
}

/**
 * The review pass. Non-fatal by construction: a revision that will not compile,
 * or that smuggles a parameter value in, is discarded and the pre-review
 * candidate stands.
 *
 * Shared by the boxed pipeline (`compileTest`) and the live one
 * (stories/compile-as-you-go.md, the Run & Compile path). `emit` receives the
 * phase message; the caller decides what frame it becomes.
 */
export async function reviewCandidate(
  candidate: Candidate,
  input: ReviewCandidateInput,
  emit: (message: string) => void,
  /** Which of the candidate's files to review. Defaults to all of them; the
   *  live path narrows it to the ones a block actually changed, so a run split
   *  across several requests does not re-review what it already passed. */
  files: string[] = candidate.touchedFiles(),
): Promise<void> {
  for (const file of files) {
    const before = candidate.contentOf(file);
    if (before === undefined) continue;
    // Before the call, not after (stories/compile-tail-progress.md). Review is
    // the longest single model call the compile makes and its first word used
    // to arrive only once it had finished — the quietest stretch of the tail
    // saying nothing at all about what it was doing.
    emit(`reviewing ${basename(file)}…`);
    let revised: string;
    try {
      const completion = await input.aiClient.complete(
        [
          buildFileReviewPrompt({
            markdownName: input.markdownName,
            file: before,
            steps: input.steps,
          }),
        ],
        input.signal,
        { profile: 'authoring' },
      );
      revised = parseFileRevision(completion.text);
    } catch (err) {
      emit(`skipped for ${basename(file)} (${(err as Error).message}) — the generated file stands`);
      continue;
    }

    if (revised.trim() === before.trim()) {
      emit(`no changes to ${basename(file)}`);
      continue;
    }

    const leaked = findInlinedParameterValue(revised, input.guarded);
    if (leaked) {
      emit(`rejected: the revision inlines ${describeGuardedName(leaked)} — the generated file stands`);
      continue;
    }
    // The reviewer edits entries; it does not decide which steps have one.
    // Caught live: given the whole test, it wrote an entry for the step a
    // prefix compile had deliberately left alone — code for a step nobody
    // recorded, which the next compile would then skip as "already has one".
    const entriesChanged = describeEntryChange(listEntries(before), listEntries(revised));
    if (entriesChanged) {
      emit(`rejected: the revision ${entriesChanged} — the generated file stands`);
      continue;
    }
    const invalid = await validateCodeBehindSource(file, revised);
    if (invalid) {
      emit(`rejected: the revision does not compile (${invalid}) — the generated file stands`);
      continue;
    }
    await candidate.replaceFile(file, revised);
    emit(`revised ${basename(file)}`);
  }
}

/**
 * How a revision changed the SET of entries, or null when it did not. Order
 * and code are the reviewer's to change; which steps have an entry is not.
 */
function describeEntryChange(
  before: Array<{ source: string; section: string }>,
  after: Array<{ source: string; section: string }>,
): string | null {
  const sep = String.fromCharCode(0);
  const key = (e: { source: string; section: string }): string => `${e.section}${sep}${e.source}`;
  const was = new Map<string, number>();
  for (const e of before) was.set(key(e), (was.get(key(e)) ?? 0) + 1);
  const now = new Map<string, number>();
  for (const e of after) now.set(key(e), (now.get(key(e)) ?? 0) + 1);
  const added = after.filter((e) => (now.get(key(e)) ?? 0) > (was.get(key(e)) ?? 0)).map((e) => e.source);
  const removed = before.filter((e) => (was.get(key(e)) ?? 0) > (now.get(key(e)) ?? 0)).map((e) => e.source);
  const quote = (sources: string[]): string => [...new Set(sources)].map((s) => JSON.stringify(s)).join(', ');
  if (added.length > 0 && removed.length > 0) {
    return `adds an entry for ${quote(added)} and removes ${quote(removed)}`;
  }
  if (added.length > 0) return `adds an entry for ${quote(added)}`;
  if (removed.length > 0) return `removes the entry for ${quote(removed)}`;
  return null;
}
