import type { ChatMessage } from '../ai/types.js';
import { decodeDoubleEscapedNewlines, extractJson } from '../ai/action-parser.js';

/**
 * The compiler's review pass (stories/codebehind-compile.md, "Review").
 *
 * One model call over the *complete* candidate file, against a checklist.
 * The characteristic bug of this feature — a model freezing today's date as a
 * literal — produces code that passes on the day it is written, so replay
 * cannot catch it. Only a reader asking "should this have been computed?" can.
 */

export interface FileReviewInput {
  /** Basename of the markdown this code-behind belongs to, for orientation. */
  markdownName: string;
  /** The candidate file, complete. */
  file: string;
  /** The test's steps, in order, so the reviewer can see what each entry is for. */
  steps: string[];
}

export function buildFileReviewPrompt(input: FileReviewInput): ChatMessage {
  const stepBlock = input.steps.length === 0
    ? '(step list unavailable)'
    : input.steps.map((s, i) => `${i + 1}. ${s}`).join('\n');

  return {
    role: 'user',
    content: `Review a generated Playwright code-behind file before it is committed.

Each entry in the file replaces one natural-language test step. The file runs
with no model call, on every future run, possibly for years.

## The test's steps
${stepBlock}

## The file, as generated
\`\`\`ts
${input.file}
\`\`\`

## The checklist

1. **Dynamic values are computed at runtime, not frozen.** A date, a derived
   code, a formatted number the step describes as a computation must be worked
   out in the code. A literal that was correct on the day of generation and
   wrong the next day is the single worst defect this file can carry — look for
   it first.
2. **Parameters are read via \`step.getVar('name')\`**, never inlined as
   literals.
3. **Every entry ends with a post-condition** — a \`locator.waitFor()\` on what
   the step produced, or a \`step.expect(...)\` over a value read back from the
   page — so "did not throw" means "the step worked".
4. **Captures are written**: a step with \`[as: x]\` must call
   \`step.setVar('x', ...)\`.
5. **Stable selectors** (ids, \`data-testid\`, roles, labels) over positional
   or index-based ones.
6. **No imports** beyond the file's existing \`defineSteps\` import, and no
   \`page.waitForTimeout\` unless it is genuinely unavoidable.
7. Leave \`source\` strings and \`section\` fields **exactly** as they are —
   they are how entries bind to steps, and an edit silently unbinds one. Never
   remove an entry.
8. An \`ai: true\` entry is a decision, not an omission: leave it alone,
   comment included. Do not turn one into a \`run\` entry, however obvious the
   code looks — something already established that this step needs the model.

## What to return

The complete revised file — not a diff, not a fragment — as one JSON string
field (standard JSON string encoding):

{
  "file": "// Generated by ai-ui-automation …\\nimport { defineSteps } …"
}

If nothing needs changing, return the file unchanged. Respond with ONLY the
JSON object — no prose around it.`,
  };
}

/**
 * Pull the revised file out of the `{"file": "..."}` envelope.
 *
 * Same double-escape decoding as the entry envelope: a model that writes
 * `\\n` inside the string leaves literal backslash-n in code position, which
 * can only ever be a syntax error.
 */
export function parseFileRevision(rawResponse: string): string {
  let body: string | undefined;
  try {
    const parsed: unknown = JSON.parse(extractJson(rawResponse));
    if (typeof parsed === 'object' && parsed !== null) {
      const file = (parsed as Record<string, unknown>)['file'];
      if (typeof file === 'string' && file.trim()) body = decodeDoubleEscapedNewlines(file);
    }
  } catch {
    // Not JSON — fall through to the fence path below.
  }

  if (body === undefined) {
    const fenced = /```(?:ts|typescript)?\s*\n([\s\S]*?)```/i.exec(rawResponse);
    if (fenced?.[1]) body = fenced[1];
  }

  const text = body?.trim();
  if (!text) throw new Error('Review response carried no revised file');
  if (!/\bdefineSteps\s*\(/.test(text)) {
    throw new Error('Review response is not a code-behind file (no `defineSteps(` call)');
  }
  return text.endsWith('\n') ? text : `${text}\n`;
}
