import * as vscode from 'vscode';
import * as fs from 'node:fs';
import * as path from 'node:path';
import {
  classifyLines,
  extractSections,
  inertRegionHeading,
  extractSteps,
  sectionBodyLinesAt,
  type StepMode,
} from 'ai-ui-automation-runner-core';
import { extractStepLineIds } from '../step-lines.js';
import type { ActiveFileTracker } from '../active-file-tracker.js';
import type { CompileOutcome, RunController, SkillDebugContext } from '../run-controller.js';
import { codeBehindPathFor, findEntryLine, type CodeBehindDiffs } from '../codebehind-diff.js';
import { getOutputChannel } from '../output-channel.js';
import { cacheDirsForTestAllEnvs } from '../cache-paths.js';
import { sectionedSkillRefusal } from '../sections.js';

interface Registry {
  active(): RunController | undefined;
  /** The currently-running controller, if any. Prefer this over
   *  `active()` for step commands when a run is in flight — see
   *  `dispatchStep` for the routing rule. */
  runningController(): RunController | undefined;
  refreshRunningContext(): void;
  notifyRunning(running: boolean): void;
  /** Phase 3.1 — drop step-paused yellow ▶ markers across every URI
   *  they live on (test file AND any skill file the run descended into). */
  clearAllStepPausedMarkers(): void;
  /** Phase 3.1.b — distinguish step-paused (server blocked on
   *  pendingRunControl) from running-but-not-step-paused (server is
   *  mid-step). dispatchStep uses this to give a clean diagnostic
   *  instead of a 409. */
  isStepPaused(controllerUri: vscode.Uri): boolean;
  /** Phase 5 — where the step-paused yellow ▶ is parked, so dispatch
   *  can detect F11-on-a-tool-line and request the tool-debugger pause. */
  stepPausedEntry(controllerUri: vscode.Uri): { uri: vscode.Uri; line: number } | null;
  /** The controller for a test document URI string, if one exists. */
  controllerForUri(uri: string): RunController | undefined;
  /** The controller holding a parked skill-step failure, if any (Stop capture). */
  controllerWithSkillFailure(): RunController | undefined;
  /** The single active "debug a skill after Stop" context, or null. */
  readonly skillDebug: SkillDebugContext | null;
  /** Set/replace the skill-debug context (latest Stop wins). */
  setSkillDebug(ctx: SkillDebugContext): void;
  /** Clear the skill-debug context unconditionally (Close Session, dead session). */
  clearSkillDebug(): void;
  /** Clear the skill-debug context only if it is owned by `testUri`. */
  clearSkillDebugIfOwnedBy(testUri: string): void;
  /** Test-only: what the most recent compile failed with, or null when it
   *  did not fail. The notification it went into is not readable from the
   *  extension host. */
  lastCompileError: string | null;
}

/**
 * Register every contributed command. Returns disposables for the activator
 * to push into context.subscriptions.
 *
 * All commands work against the *active TextEditor*. The
 * `testbench-native.activeFile` context key (set by ActiveFileTracker) gates menu
 * visibility so users can't invoke them on non-test markdown.
 */
export function registerCommands(
  registry: Registry,
  tracker: ActiveFileTracker,
  diffs: CodeBehindDiffs,
): vscode.Disposable[] {
  /**
   * Run & Compile, and Compile This Step (stories/compile-as-you-go.md).
   *
   * Both are runs first: the test (or the clicked step) executes through the
   * ordinary run machinery in the document's own session — same browser
   * window, same gutter, breakpoints and Stop all working — with `compile` on
   * the request. Entries are generated by a queue trailing the run, and the
   * proposal comes back on the run's outcome for the diff.
   *
   * There is no Record and no Replay. The entries are born unproven, which is
   * what the summary says: the author's next ordinary Run proves each one
   * (the code mark) or flags it (⚠ stale).
   *
   * Shared by the whole-test command, the panel's Compile button and the
   * one-step gutter command: they differ only in `mode` and which lines run.
   */
  const runAndCompile = async (options: {
    /** Lines to run. Empty means the whole test, as Run All does. */
    lines?: number[];
    mode?: 'run' | 'steps';
    /** The `### Section` the steps were authored in, when they came from a
     *  body. Their ENTRIES bind under it; they still execute detached. */
    section?: string;
  } = {}): Promise<void> => {
    const controller = registry.active();
    if (!controller) return notifyNoActive();
    registry.lastCompileError = null;
    if (controller.isRunning) {
      // Recorded, not just shown: a notification is not readable from the
      // extension host, and this refusal is the one a test has to be able to
      // tell apart from "the request went out and failed".
      const refusal =
        'Cannot compile while a run of this test is in progress. Stop it, or wait for it to finish.';
      registry.lastCompileError = refusal;
      void vscode.window.showWarningMessage(refusal);
      return;
    }
    // The proposal's diff is against the file on disk, and the recording lands
    // beside it. An unsaved buffer would offer a diff against something the
    // author is not looking at.
    if (controller.document.isDirty) {
      await controller.document.save();
    }
    const mode = options.mode ?? 'run';
    const lines = options.lines ?? [];
    const label = path.basename(controller.document.uri.fsPath);

    registry.notifyRunning(true);
    let result;
    try {
      result = await controller.runLines(lines, {
        // Run & Compile honours breakpoints — it is a run the author wanted to
        // watch. Compile This Step does not: the author named the steps to
        // compile, and pausing before one of them would propose nothing for it.
        ...(mode === 'run' && { breakpoints: tracker.breakpoints(controller.document.uri) }),
        ...(mode === 'steps' && { skipBreakpointAtStart: true }),
        compile: mode,
        ...(options.section !== undefined && { compileScope: { section: options.section } }),
      });
    } finally {
      registry.notifyRunning(false);
    }

    // A run that stopped at a breakpoint has not finished compiling: the
    // compiler is still open on the session and Continue will send the rest.
    // Opening a diff now would interrupt the debugging session the breakpoint
    // exists for, and offer a proposal that is about to grow.
    if (controller.isParkedAtPause) {
      vscode.window.setStatusBarMessage(
        'TestBench: paused at a breakpoint — Continue to finish compiling',
        5000,
      );
      return;
    }
    await presentCompile(controller, label, result);
  };

  /**
   * Show what a compile-mode run came back with: the diff, and a notification
   * that says what is in it.
   *
   * Separate from `runAndCompile` because Continue reaches here too — a run
   * paused at a breakpoint finishes on a later `runLines` call, and the fuller
   * proposal that call produces would otherwise be collected and dropped.
   */
  const presentCompile = async (
    controller: RunController,
    label: string,
    result: { ok: boolean; error?: { message: string }; compile?: CompileOutcome },
  ): Promise<void> => {
    const outcome = result.compile;
    if (!outcome && !result.ok && result.error) {
      // The run never got going — the server was down, the port belongs to
      // something else, the key was refused. The run path already said so, in
      // the catalogue's words and with the fix attached; a compile failure is
      // not a second vocabulary for the same problem.
      registry.lastCompileError = result.error.message;
      return;
    }
    if (!outcome) {
      // The run happened; the compile did not answer. An older server (one
      // that drops `compile` off the allow-list) looks exactly like this, and
      // saying so beats a silent no-op.
      registry.lastCompileError = 'the run produced no compile result';
      void vscode.window
        .showWarningMessage(
          `${label} ran, but nothing came back to compile. Is the server on a build that supports Run & Compile?`,
          'Show log',
        )
        .then((choice) => {
          if (choice === 'Show log') getOutputChannel().show(true);
        });
      return;
    }

    // The summary notification is never awaited — a compile is finished when
    // the diff is on screen, and blocking the command on a click would leave
    // the caller (and every test) waiting on the user.
    if (!outcome.ok) {
      registry.lastCompileError = outcome.error ?? 'unknown error';
      const s = outcome.summary;
      const actions = ['Show log', ...(s?.recordingDir ? ['Open recording'] : [])];
      if (s?.candidatePath) actions.push('Open candidate');
      void vscode.window
        .showErrorMessage(
          `Compile failed for ${label}: ${outcome.error ?? 'unknown error'}`,
          ...actions,
        )
        .then(async (choice) => {
          if (choice === 'Show log') getOutputChannel().show(true);
          if (choice === 'Open recording' && s?.recordingDir) await revealRecording(s.recordingDir);
          if (choice === 'Open candidate' && s?.candidatePath) {
            const doc = await vscode.workspace.openTextDocument(vscode.Uri.file(s.candidatePath));
            await vscode.window.showTextDocument(doc, { preview: false });
          }
        });
      return;
    }

    const files = outcome.files ?? {};
    const summary = outcome.summary;
    if (Object.keys(files).length === 0) {
      vscode.window.showInformationMessage(
        `Nothing to compile in ${label} — every step already has code-behind.`,
      );
      return;
    }

    await diffs.open({ testFilePath: controller.document.uri.fsPath, files });
    const tokens = summary ? summary.tokensUsed.toLocaleString() : '?';
    const compiled = summary?.compiled ?? 0;
    const total = summary?.totalSteps ?? 0;
    const keptAi = summary?.keptAi ?? 0;
    // What is missing and what to do about it: the step the run stopped at
    // and the steps it never reached. `unproven` is dropped from the notes
    // because on this path it is *every* entry — the headline says so once,
    // rather than listing them all again (stories/compile-as-you-go.md
    // §Proof, not Replay).
    const partial =
      outcome.status === 'partial' && summary ? partialNotes({ ...summary, unproven: [] }) : '';
    const show = outcome.status === 'partial'
      ? vscode.window.showWarningMessage
      : vscode.window.showInformationMessage;
    void show(
        `Compiled ${label}: ${compiled} of ${total} step(s) as code ` +
          '(unproven — the next run proves them)' +
          (keptAi > 0 ? `, ${keptAi} kept AI` : '') +
          `.${partial} Used ${tokens} tokens.`,
        'Apply',
        'Open diff',
        'Open recording',
        'Show log',
      )
      .then(async (choice) => {
        if (choice === 'Apply') {
          await vscode.commands.executeCommand('testbench-native.applyCodeBehind');
        }
        if (choice === 'Open diff') {
          await diffs.open({ testFilePath: controller.document.uri.fsPath, files });
        }
        if (choice === 'Open recording' && summary?.recordingDir) await revealRecording(summary.recordingDir);
        if (choice === 'Show log') getOutputChannel().show(true);
      });
  };
  const runSelected = async (): Promise<void> => {
    const controller = registry.active();
    const editor = tracker.activeEditor;
    if (!controller || !editor) return notifyNoActive();
    // selectionLines returns [] for cursor-only "selections" (no
    // highlighted range), which runLines interprets as "run every step in
    // the document" — the same behavior as Run All. See selectionLines'
    // doc comment for why.
    const lines = selectionLines(editor);
    // A selection of nothing but inert items would reach `runLines`, resolve
    // to no steps, and surface as TB025 ("that selection named no step") —
    // true, and no help at all. A mixed selection is left alone: the real
    // steps run and the inert ones are dropped, which is what the author
    // asked for. Contract §5 rule 4a.
    const text = editor.document.getText();
    const inertOnly =
      lines.length > 0 && lines.every((l) => inertLineRefusal(text, l) !== null);
    if (inertOnly) {
      vscode.window.showWarningMessage(inertLineRefusal(text, lines[0]!)!);
      return;
    }
    const breakpoints = tracker.breakpoints(controller.document.uri);
    registry.notifyRunning(true);
    await controller.runLines(lines, { breakpoints }).finally(() => registry.notifyRunning(false));
  };

  /**
   * Fully stop the active run and wipe its UI state. Shared by the Stop
   * command and Close Session — closing a session while a run is in flight
   * (or paused awaiting Continue) must first tear the run down, otherwise
   * spinners and the yellow ▶ stay painted with no session behind them.
   */
  const performStop = (opts: { setSkillDebug?: boolean } = {}): void => {
    const controller = registry.active();
    // On an explicit Stop (not Close Session), park a skill-debug context for a
    // parked TOP-LEVEL skill failure — read BEFORE resetFrameState wipes
    // lastSkillFailure. Latest Stop wins (setSkillDebug replaces any prior).
    if (opts.setSkillDebug) {
      const failed = controller?.lastSkillFailure
        ? controller
        : registry.controllerWithSkillFailure();
      const f = failed?.lastSkillFailure;
      // Skill failures only. "Debug a skill after Stop" opens the skill file
      // and runs its body against the stopped session — for a SECTION,
      // `skillUri` is the test file itself, so that flow would activate
      // against the wrong thing entirely: it would offer to debug "the skill"
      // by reopening the test the user is already looking at. Section re-runs
      // go through the Variables panel path instead, which needs no such
      // context.
      if (f && f.kind === 'skill') {
        registry.setSkillDebug({
          testUri: f.testUri,
          testLine: f.testLine,
          skillUri: f.skillUri,
          skillName: f.skillName,
          frameId: f.frameId,
        });
      }
    }
    controller?.stop();
    // Stop must flip running statuses on BOTH the test file and any skill
    // file the run descended into — otherwise skill-body lines keep
    // spinning. Frame state on the controller is wiped too so a subsequent
    // run doesn't inherit stale frames.
    controller?.resetFrameState();
    const editor = tracker.activeEditor;
    if (editor && tracker.isActiveTestFile) {
      tracker.setBreakpointStop(editor.document.uri, null);
    }
    tracker.markAllRunningStopped();
    // A step-paused yellow ▶ may live on a SKILL file the run descended
    // into — `setBreakpointStop` above only cleared the test-file marker.
    // Walk every recorded step-paused entry and clear it where painted.
    registry.clearAllStepPausedMarkers();
    registry.notifyRunning(false);
  };

  return [
    vscode.commands.registerCommand('testbench-native.runSelected', runSelected),

    vscode.commands.registerCommand('testbench-native.runAll', async () => {
      const controller = registry.active();
      if (!controller) return notifyNoActive();
      const breakpoints = tracker.breakpoints(controller.document.uri);
      registry.notifyRunning(true);
      await controller
        .runLines([], { breakpoints })
        .finally(() => registry.notifyRunning(false));
    }),

    vscode.commands.registerCommand('testbench-native.pause', () => {
      const controller = registry.active();
      if (!controller || !controller.isRunning) {
        vscode.window.setStatusBarMessage('TestBench: nothing to pause', 1500);
        return;
      }
      controller.pause();
      // Pause leaves the in-flight step's status as `running` (blue spinner)
      // unless we flip it. The spinner spins forever on whichever file the
      // step belonged to — most visibly on a skill body line, where the
      // yellow ▶ doesn't even live on the same file. Same wipe Stop uses
      // (running → stopped across every tracked URI) is the right move here:
      // the step was interrupted mid-flight, so it isn't passing, failing,
      // or still executing.
      tracker.markAllRunningStopped();
    }),

    vscode.commands.registerCommand('testbench-native.stop', () => {
      performStop({ setSkillDebug: true });
    }),

    // "Debug a skill against a stopped session": run the selected skill step(s)
    // (or the whole skill body if nothing is selected) against the still-live
    // session of the test that was Stopped inside this skill. Routes through the
    // owning test's controller so the open browser + live variables are reused.
    // See stories/specs/skill-debug-after-stop.md.
    vscode.commands.registerCommand('testbench-native.runSkillStepsOnStoppedSession', async () => {
      const ctx = registry.skillDebug;
      if (!ctx) {
        vscode.window.setStatusBarMessage(
          'TestBench: no stopped skill to debug — Stop a test that failed inside a skill first',
          3000,
        );
        return;
      }
      const editor = tracker.activeEditor;
      if (!editor || vscode.Uri.file(ctx.skillUri).toString() !== editor.document.uri.toString()) {
        vscode.window.setStatusBarMessage(
          `TestBench: open the skill being debugged (${ctx.skillName}) to run its steps`,
          3000,
        );
        return;
      }
      // Range = the selected step lines, or the whole skill body when nothing is
      // selected. `extractSteps` keys on the `## Steps` list, which skills have;
      // its line model matches the server's expanded source lines.
      const steps = extractSteps(editor.document.getText());
      if (steps.length === 0) {
        vscode.window.setStatusBarMessage('TestBench: no steps found in this skill', 2500);
        return;
      }
      const bodyLines = steps.map((s) => s.line);
      const stepLineSet = new Set(bodyLines);
      const selected = selectionLines(editor).filter((l) => stepLineSet.has(l));
      const targetLines = selected.length > 0 ? selected : bodyLines;
      const startLine = targetLines[0]!;
      const endLine = targetLines[targetLines.length - 1]!;

      const controller = registry.controllerForUri(ctx.testUri.toString());
      if (!controller) {
        registry.clearSkillDebug();
        vscode.window.setStatusBarMessage('TestBench: the stopped test is no longer open', 3000);
        return;
      }
      // Liveness pre-flight BEFORE notifyRunning — a dead session must refuse
      // (and clear the context) rather than silently spin up a blank browser.
      const live = await controller.isRerunSessionLive();
      if (!live) {
        registry.clearSkillDebug();
        vscode.window.setStatusBarMessage(
          'TestBench: the stopped session is no longer alive — re-run the test to debug again',
          4000,
        );
        return;
      }
      // Same anchoring hazard as the Variables-panel re-run: a skill that
      // defines its own sections cannot be line-anchored safely, because the
      // server applies exact matching only to the test file and falls back to
      // nearest-line in a skill — landing inside a body that already ran.
      // This context is skill-kind by construction (it comes from the Stop
      // gate, which only captures skill failures).
      const unsupported = sectionedSkillRefusal({
        kind: 'skill',
        skillUri: ctx.skillUri,
        skillName: ctx.skillName,
      });
      if (unsupported) {
        vscode.window.setStatusBarMessage(unsupported, 6000);
        return;
      }
      registry.notifyRunning(true);
      void controller
        .runLines([ctx.testLine], {
          isContinuation: true,
          rerun: {
            startAt: { uri: ctx.skillUri, line: startLine },
            endAt: { uri: ctx.skillUri, line: endLine },
          },
        })
        .finally(() => registry.notifyRunning(false));
    }),

    // ── Phase 3 step controls ────────────────────────────────────────
    //
    // The three step commands share dispatch logic:
    //  - If a step:awaiting run is in flight (stepPaused), POST a
    //    run-control to advance.
    //  - If a breakpoint pause is set (the run isn't in flight; the
    //    extension trimmed at a breakpoint), launch a fresh run from
    //    that line with the requested stepMode — Step Into starts a
    //    stepping session.
    //  - Step Into from a fully idle state launches a new run with
    //    stepMode='into' starting at the cursor/selection. Step Over /
    //    Step Out from idle are surface-only no-ops with a status
    //    message — they only have meaning once you're inside a run.
    vscode.commands.registerCommand('testbench-native.stepInto', () =>
      dispatchStep('into', registry, tracker),
    ),
    vscode.commands.registerCommand('testbench-native.stepOver', () =>
      dispatchStep('over', registry, tracker),
    ),
    vscode.commands.registerCommand('testbench-native.stepOut', () =>
      dispatchStep('out', registry, tracker),
    ),
    // Unified Continue (matches VS Code's standard debugger
    // convention — one Continue regardless of how you got paused):
    //   - Step-paused (mid stepping run, server blocked on
    //     pendingRunControl): POST run-control with mode='continue'.
    //     Drains the rest of the run or hits the next breakpoint.
    //   - Breakpoint-paused (run trimmed at a breakpoint, no SSE
    //     stream open): re-open the stream from the pause line and
    //     run through to the end of the document or the next break.
    // The `testbench-native.resume` command stays as a back-compat
    // alias for any user keybindings + existing integration tests
    // that call it by name.
    vscode.commands.registerCommand('testbench-native.continueRun', async () => {
      // Same routing rule as `dispatchStep`: prefer the running
      // controller so Continue from a side-by-side skill file
      // advances the outer run instead of trying to relaunch the
      // skill file as a new test.
      const controller = registry.runningController() ?? registry.active();
      const editor = tracker.activeEditor;
      if (!controller || !editor) return notifyNoActive();

      // Step-paused branch — fast path: deliver the next mode via
      // run-control. The controller's `isRunning` is still true in
      // this state (SSE stream is open, just blocked on a Promise).
      if (controller.isRunning && registry.isStepPaused(controller.document.uri)) {
        await controller.sendRunControl('continue');
        return;
      }

      // Breakpoint-paused branch — re-open the stream. Read the anchor-derived
      // current line (not the raw pause-time line) so edits made while paused
      // resume the step the user actually paused on.
      const startLine = tracker.breakpointStopFor(controller.document.uri);
      const sectionCtx = tracker.resumeContextFor(controller.document.uri);
      if (startLine != null && !controller.isRunning) {
        tracker.setBreakpointStop(controller.document.uri, null);
        const breakpoints = tracker.breakpoints(controller.document.uri);
        // A marker parked inside a section body resumes THAT step, not the
        // invocation above it. The context is also the discriminator: a body
        // line without one is a marker we can't resume (dropped stream,
        // restarted server) and still falls through to the refusal below.
        if (sectionCtx) {
          const plan = sectionResumePlan(
            editor.document.getText(),
            startLine,
            sectionCtx.callLine,
            controller.document.uri.fsPath,
          );
          if (!plan) {
            refuseStaleResume(tracker, controller.document.uri);
            return;
          }
          registry.notifyRunning(true);
          await controller
            .runLines(plan.lines, {
              breakpoints,
              skipBreakpointAtStart: true,
              isContinuation: true,
              ...(plan.rerun && { rerun: plan.rerun }),
            })
            .finally(() => registry.notifyRunning(false));
          return;
        }
        // Continue runs from startLine to end-of-document. Passing
        // `[startLine]` alone would collapse through resolveRunLines
        // to a one-step run — useful for Step Over but not Continue.
        const resumeLines = extractSteps(editor.document.getText())
          .map((s) => s.line)
          .filter((line) => line >= startLine);
        if (resumeLines.length === 0) {
          refuseStaleResume(tracker, controller.document.uri);
          return;
        }
        registry.notifyRunning(true);
        const resumed = await controller
          .runLines(resumeLines, { breakpoints, skipBreakpointAtStart: true, isContinuation: true })
          .finally(() => registry.notifyRunning(false));
        // A Continue inherits the compile mode of the run it is continuing
        // (see `compileModeOfRun`), so it can be the block that finishes a
        // Run & Compile. Its proposal is the fullest one — collected and then
        // dropped, before this.
        if (resumed.compile && !controller.isParkedAtPause) {
          await presentCompile(
            controller,
            path.basename(controller.document.uri.fsPath),
            resumed,
          );
        }
        return;
      }

      vscode.window.setStatusBarMessage('TestBench: nothing to continue', 2000);
    }),

    // Back-compat alias: `testbench-native.resume` delegates to
    // continueRun. Existing tests and user-configured keybindings
    // keep working unchanged.
    //
    // NOTE: renaming or removing `testbench-native.continueRun`
    // silently breaks this alias with a runtime "command not found"
    // (the registration happens at activation; there's no compile-
    // time link between the two command IDs).
    vscode.commands.registerCommand('testbench-native.resume', () =>
      vscode.commands.executeCommand('testbench-native.continueRun'),
    ),

    vscode.commands.registerCommand('testbench-native.restartSession', async () => {
      const controller = registry.active();
      if (!controller) return notifyNoActive();
      // Close Session must also stop the test: a run that's in flight (or
      // paused awaiting Continue) otherwise keeps its spinners / yellow ▶
      // painted after the session is gone, and a later Continue would spin
      // up a brand-new session against stale UI state.
      performStop();
      // Closing this test's session ends its debug context (page is gone).
      registry.clearSkillDebugIfOwnedBy(controller.document.uri.toString());
      await controller.closeSession();
      vscode.window.setStatusBarMessage(
        'TestBench: session closed — next F5 starts a fresh browser',
        3000,
      );
    }),

    vscode.commands.registerCommand('testbench-native.toggleBreakpoint', (target?: { lineNumber?: number }) => {
      const editor = tracker.activeEditor;
      if (!editor || !tracker.isActiveTestFile) return notifyNoActive();

      // Editor lineNumber context menus pass `{ lineNumber }` (1-based).
      // Keybindings have no argument; fall back to the cursor's line.
      const line =
        typeof target?.lineNumber === 'number'
          ? target.lineNumber
          : editor.selection.active.line + 1;

      const stepIds = new Set(extractStepLineIds(editor.document.getText()));
      if (!stepIds.has(line)) {
        vscode.window.setStatusBarMessage(
          'TestBench: breakpoints can only sit on numbered step lines',
          2500,
        );
        return;
      }
      tracker.toggleBreakpoint(editor.document.uri, line);
    }),

    vscode.commands.registerCommand('testbench-native.runStepHere', (target?: { lineNumber?: number }) => {
      const editor = tracker.activeEditor;
      const controller = registry.active();
      if (!editor || !controller) return notifyNoActive();
      const line =
        typeof target?.lineNumber === 'number'
          ? target.lineNumber
          : editor.selection.active.line + 1;
      const inert = inertLineRefusal(editor.document.getText(), line);
      if (inert) {
        vscode.window.showWarningMessage(inert);
        return;
      }
      const breakpoints = tracker.breakpoints(controller.document.uri);
      registry.notifyRunning(true);
      void controller
        .runLines([line], { breakpoints })
        .finally(() => registry.notifyRunning(false));
    }),

    vscode.commands.registerCommand('testbench-native.clearBreakpoints', () => {
      const editor = tracker.activeEditor;
      if (!editor) return notifyNoActive();
      tracker.clearBreakpoints(editor.document.uri);
    }),

    vscode.commands.registerCommand('testbench-native.clearStatuses', () => {
      const editor = tracker.activeEditor;
      if (!editor) return notifyNoActive();
      tracker.clearStatuses(editor.document.uri);
    }),

    // Wipes <project-root>/.cache/<env>/<dir>/ for the active test across EVERY
    // env segment, not just the active one. A single file can populate multiple
    // segments: an interactive run uses the EnvSelector's active env, while a
    // batch run keys off the test's frontmatter env (test-controller.ts's
    // `frontmatter.env ?? batchEnv`), so the same file may have written
    // `.cache/dev/<dir>/` AND `.cache/staging/<dir>/`. Clearing only the active
    // env's entry would silently leave the others stale (issue 012 gap), so this
    // enumerates all segments — "clear" means clear. Skill steps invoked from
    // this test live in the same dir (the cache is keyed off the test file, not
    // per-skill) so they go too. Bundle-hash invalidation already covers "I
    // edited a step" — this command is for the cases the hash can't see: env
    // values changed, model upgraded, real-world page drift on a step that
    // scrapes a live site, etc.
    vscode.commands.registerCommand('testbench-native.clearCacheForThisTest', async () => {
      const editor = tracker.activeEditor;
      if (!editor) return notifyNoActive();
      const testFilePath = editor.document.uri.fsPath;
      const cacheDirs = cacheDirsForTestAllEnvs(testFilePath);
      if (cacheDirs.length === 0) {
        vscode.window.setStatusBarMessage(
          'TestBench: no cache to clear for this test',
          2000,
        );
        return;
      }
      const fileLabel = path.basename(testFilePath);
      const detail =
        cacheDirs.length === 1
          ? `This removes ${cacheDirs[0]}.\n\nThe next run will call the AI again to repopulate it.`
          : `This removes ${cacheDirs.length} cached env entries:\n${cacheDirs.join('\n')}\n\nThe next run will call the AI again to repopulate them.`;
      const choice = await vscode.window.showWarningMessage(
        `Delete cached AI responses for ${fileLabel}?`,
        { modal: true, detail },
        'Delete',
      );
      if (choice !== 'Delete') return;
      const failed: string[] = [];
      for (const dir of cacheDirs) {
        try {
          fs.rmSync(dir, { recursive: true, force: true });
          getOutputChannel().appendLine(`Cleared step cache: ${dir}`);
        } catch (err) {
          failed.push(`${dir} — ${err instanceof Error ? err.message : String(err)}`);
        }
      }
      if (failed.length > 0) {
        vscode.window.showErrorMessage(
          `TestBench: failed to clear cache — ${failed.join('; ')}`,
        );
        return;
      }
      vscode.window.setStatusBarMessage(`TestBench: cleared cache for ${fileLabel}`, 3000);
    }),

    // Run & Compile (stories/compile-as-you-go.md). One flow, two ids: the
    // new name, and the old `compileCodeBehind` — which the panel's Compile
    // button and every existing keybinding still execute — repointed at it.
    // The boxed Record/Replay pipeline stays server-side for `aiui compile`
    // and is no longer reachable from the extension.
    vscode.commands.registerCommand('testbench-native.runAndCompile', () => runAndCompile()),
    vscode.commands.registerCommand('testbench-native.compileCodeBehind', () => runAndCompile()),

    // "Compile This Step" — the clicked step (or each step in a multi-line
    // selection, or the body a `### Section` / `[skill:]` call expands to)
    // runs NOW in the document's live session, from wherever the browser is,
    // and that fresh run is the recording (stories/compile-as-you-go.md
    // §Compile This Step). No step numbers are involved, so the old refusal
    // for a step below a skill or section call is gone: this binds by what the
    // runtime binds by — the step's authored text plus its section scope.
    vscode.commands.registerCommand(
      'testbench-native.compileStepCodeBehind',
      async (target?: { lineNumber?: number }) => {
        const editor = tracker.activeEditor;
        if (!editor) return notifyNoActive();
        const line =
          typeof target?.lineNumber === 'number'
            ? target.lineNumber
            : editor.selection.active.line + 1;
        // A multi-line selection that covers the clicked line compiles every
        // step in it, in order — the session advances between them, so a
        // selection is just this flow k times. The resolver also decides the
        // scope the entries bind under, which for a section body is not the
        // scope the steps EXECUTE in.
        const target2 = resolveCompileTarget(
          editor.document.getText(),
          line,
          selectionLines(editor),
        );
        if (!target2.ok) {
          // Recorded as well as shown: a notification is not readable from the
          // extension host, and these refusals are the ones a test has to be
          // able to tell apart from "the request went out".
          registry.lastCompileError = target2.refusal;
          vscode.window.showWarningMessage(target2.refusal);
          return;
        }
        await runAndCompile({
          lines: target2.lines,
          mode: 'steps',
          ...(target2.section !== undefined && { section: target2.section }),
        });
      },
    ),

    // "Open Code-behind" — the counterpart of Go to Section: from a step, to
    // the entry that implements it in the sibling `.steps.ts`.
    vscode.commands.registerCommand(
      'testbench-native.openCodeBehind',
      async (target?: { lineNumber?: number }) => {
        const editor = tracker.activeEditor;
        if (!editor) return notifyNoActive();
        const line =
          typeof target?.lineNumber === 'number'
            ? target.lineNumber
            : editor.selection.active.line + 1;
        const step = extractSteps(editor.document.getText()).find((s) => s.line === line);
        if (!step) {
          vscode.window.showWarningMessage(
            'TestBench: that line is not a step, so it has no code-behind.',
          );
          return;
        }
        const file = codeBehindPathFor(editor.document.uri.fsPath);
        if (!fs.existsSync(file)) {
          const choice = await vscode.window.showInformationMessage(
            `No code-behind yet for ${path.basename(editor.document.uri.fsPath)}.`,
            'Run & Compile',
          );
          if (choice === 'Run & Compile') await runAndCompile();
          return;
        }
        const doc = await vscode.workspace.openTextDocument(vscode.Uri.file(file));
        const entryLine = findEntryLine(doc.getText(), step.instruction);
        const shown = await vscode.window.showTextDocument(doc, { preview: false });
        if (entryLine === null) {
          vscode.window.setStatusBarMessage(
            'TestBench: this step has no entry yet — compile it',
            3000,
          );
          return;
        }
        const pos = new vscode.Position(entryLine - 1, 0);
        shown.selection = new vscode.Selection(pos, pos);
        shown.revealRange(new vscode.Range(pos, pos), vscode.TextEditorRevealType.InCenter);
      },
    ),

    vscode.commands.registerCommand('testbench-native.applyCodeBehind', async () => {
      // Read before applying — `apply` consumes the proposal.
      const testFilePath = diffs.pending?.testFilePath;
      const written = await diffs.apply();
      if (written.length === 0) {
        vscode.window.setStatusBarMessage('TestBench: nothing to apply', 2000);
        return;
      }
      const names = written.map((f) => path.basename(f)).join(', ');
      getOutputChannel().appendLine(`Applied code-behind: ${written.join(', ')}`);
      // Back to the test. Every TestBench command works against the active
      // editor, and the diff this was invoked from is not a test file — so
      // without this the author's next act (Run, to see the code marks) silently
      // does nothing.
      if (testFilePath) {
        const doc = await vscode.workspace.openTextDocument(vscode.Uri.file(testFilePath));
        await vscode.window.showTextDocument(doc, { preview: false });
      }
      vscode.window.setStatusBarMessage(`TestBench: applied ${names}`, 3000);
    }),

    vscode.commands.registerCommand('testbench-native.discardCodeBehind', async () => {
      await diffs.discard();
      vscode.window.setStatusBarMessage('TestBench: discarded the compiled code-behind', 2000);
    }),

    vscode.commands.registerCommand('testbench-native.revealEnvFile', async () => {
      const controller = registry.active();
      if (!controller) return notifyNoActive();
      const path = controller.lastEnvPath;
      if (!path) {
        vscode.window.setStatusBarMessage(
          'TestBench: no .env resolved yet — run a test first',
          3000,
        );
        return;
      }
      await vscode.commands.executeCommand('revealFileInOS', vscode.Uri.file(path));
    }),

    // Opens the HTML report from the most recently completed run for the
    // active test file. The server writes the report and announces the
    // path via the `done` event's optional `reportPath` field — see the
    // Open Last Report spec under stories/specs/. We use openExternal so
    // the file launches in the user's default browser; VS Code's preview
    // is markdown-only and the report uses CSS + linked screenshots that
    // only render correctly in a real browser.
    vscode.commands.registerCommand('testbench-native.openLastReport', async () => {
      const controller = registry.active();
      if (!controller) return notifyNoActive();
      const reportPath = controller.lastReportPath;
      if (!reportPath) {
        vscode.window.setStatusBarMessage(
          'TestBench: no report yet — run a test first',
          3000,
        );
        return;
      }
      if (!fs.existsSync(reportPath)) {
        vscode.window.setStatusBarMessage(
          `TestBench: report file no longer exists at ${reportPath}`,
          4000,
        );
        return;
      }
      await vscode.env.openExternal(vscode.Uri.file(reportPath));
    }),

    vscode.commands.registerCommand('testbench-native.showRunLog', () => {
      getOutputChannel().show(true);
    }),

    vscode.commands.registerCommand('testbench-native.dismissError', () => {
      // No-op host side — the webview owns the banner state.
    }),

    vscode.commands.registerCommand('testbench-native.focusRunner', async () => {
      await vscode.commands.executeCommand('testbench-native.runner.focus');
    }),
  ];
}

/**
 * 1-based line numbers covered by every *range* selection in the editor.
 * Cursor-only "selections" (no highlighted range) are ignored: a cursor
 * just means "I'm parked here," not "run this." See the same helper in
 * active-file-tracker.ts for the full rationale.
 */
function selectionLines(editor: vscode.TextEditor): number[] {
  const set = new Set<number>();
  for (const sel of editor.selections) {
    if (sel.isEmpty) continue;
    const start = sel.start.line;
    const end = sel.end.line;
    for (let i = start; i <= end; i++) set.add(i + 1);
  }
  return [...set].sort((a, b) => a - b);
}

function notifyNoActive(): void {
  vscode.window.setStatusBarMessage(
    'TestBench: open a Markdown file with a "## Steps" heading first',
    2500,
  );
}

/**
 * What Compile This Step should send for a click at `line`, or why it cannot
 * (stories/compile-as-you-go.md §Compile This Step).
 *
 * What is ALLOWED: a plain step, a `### Section` or `[skill:]` call line, a
 * step below either of those, and a step inside a section body. The body case
 * is why this returns a scope rather than a boolean: the step runs detached at
 * the root frame, as Run Step Here runs it, but its ENTRY has to bind under
 * the section — that is where the runtime, which reaches the step through the
 * section, looks for it.
 *
 * What is refused is refused because compiling it would produce a WRONG entry,
 * not because the feature is missing — see each branch.
 */
export type CompileTarget =
  | { ok: true; lines: number[]; section?: string }
  | { ok: false; refusal: string };

/**
 * Why this line cannot be run or compiled because it is inert, or null.
 *
 * A numbered item under a `####` heading looks exactly like a step. Nothing
 * runs it (sections contract §5 rule 4a), so every entry point that would
 * otherwise send it to the server says so instead of quietly doing nothing —
 * an empty selection reaching `runLines` surfaces as TB025 ("that selection
 * named no step"), which is true and unhelpful.
 */
export function inertLineRefusal(text: string, line: number): string | null {
  const owner = inertRegionHeading(text, line);
  if (!owner) return null;
  return (
    `TestBench: that step never runs — steps under a '####' heading ("${owner.name}", ` +
    `line ${owner.line}) are ignored. Use '###' to define a section, then call it ` +
    'by name from the main flow.'
  );
}

export function resolveCompileTarget(
  text: string,
  clicked: number,
  selected: number[],
): CompileTarget {
  const classified = classifyLines(text);
  const kindOf = (line: number): string | undefined => classified[line - 1]?.kind;
  const clickedKind = kindOf(clicked);
  if (clickedKind === 'inert-step') {
    return { ok: false, refusal: inertLineRefusal(text, clicked)! };
  }
  if (clickedKind !== 'step' && clickedKind !== 'section-step') {
    return { ok: false, refusal: 'TestBench: that line is not a step. Put the cursor on a numbered step.' };
  }

  // A multi-line selection that covers the clicked line compiles every step in
  // it, in order; anything else is just the clicked line.
  const lines =
    selected.length > 1 && selected.includes(clicked)
      ? selected.filter((l) => kindOf(l) === 'step' || kindOf(l) === 'section-step')
      : [clicked];

  // One scope per compile. A selection spanning a section body and the main
  // flow — or two different sections — has no single `section:` to stamp, and
  // guessing one would put half the entries where nothing looks for them.
  const scopes = new Set(lines.map((l) => sectionOwningLine(text, l) ?? ''));
  if (scopes.size > 1) {
    const named = [...scopes].map((s) => (s === '' ? 'the main flow' : `"${s}"`)).sort();
    return {
      ok: false,
      refusal:
        `TestBench: that selection spans ${named.join(' and ')}, and each entry binds to one ` +
        'scope. Select steps from one section body, or from the main flow.',
    };
  }
  const section = [...scopes][0] ?? '';

  // Occurrence is counted within the request, so a compile that sends SOME of
  // a repeated text's occurrences numbers them from 0 — and the entry lands on
  // the wrong one, replacing code generated from a different step. Sending all
  // of them is fine: they number correctly.
  const siblings = section === '' ? rootFrameSteps(text) : sectionBodySteps(text, section);
  for (const line of lines) {
    const self = siblings.find((s) => s.line === line);
    if (!self) continue;
    const same = siblings.filter((s) => s.instruction === self.instruction);
    if (same.length > 1 && !same.every((s) => lines.includes(s.line))) {
      return {
        ok: false,
        refusal:
          `TestBench: "${self.instruction}" appears more than once in ` +
          `${section === '' ? 'this test' : `"${section}"`}, and a partial compile cannot tell ` +
          'which one you mean — the entry would land on the first. Select them all, or use Run & Compile.',
      };
    }
  }

  return { ok: true, lines, ...(section !== '' && { section }) };
}

/**
 * The main-flow steps that survive expansion as steps of the TEST's own frame
 * — the population an entry's `occurrence` is counted over.
 *
 * A bare section call and a `[skill: ...]` invocation are replaced by their
 * bodies, which bind inside their own frames, so neither contributes a
 * root-frame step and neither can collide with one.
 */
function rootFrameSteps(text: string): { line: number; instruction: string }[] {
  const sectionNames = new Set(extractSections(text).map((s) => s.name.trim().toLowerCase()));
  return extractSteps(text)
    .map((s) => ({ line: s.line, instruction: s.instruction.trim() }))
    .filter(
      (s) =>
        !/^\[\s*skill\s*:/i.test(s.instruction) && !sectionNames.has(s.instruction.toLowerCase()),
    );
}

/** The steps of one `### Section` body — the occurrence population for an
 *  entry that binds under that section's scope. */
function sectionBodySteps(text: string, section: string): { line: number; instruction: string }[] {
  const found = extractSections(text).find((s) => s.name === section);
  return (found?.steps ?? []).map((s) => ({ line: s.line, instruction: s.instruction.trim() }));
}

/** The name of the `### Section` whose body contains `line`, if any. */
function sectionOwningLine(text: string, line: number): string | null {
  for (const section of extractSections(text)) {
    if (section.steps.some((s) => s.line === line)) return section.name;
  }
  return null;
}

/**
 * True when the controller's step-paused yellow ▶ is parked on a
 * `[tool: ...]` invocation. Reads the document at the paused line.
 * Returns false on any miss (no pause, document not open, no match) —
 * the caller falls back to normal stepInto behaviour, which is correct
 * for skill lines and inline AI steps.
 */
function isAtToolLine(registry: Registry, controller: RunController): boolean {
  const entry = registry.stepPausedEntry(controller.document.uri);
  if (!entry) return false;
  const doc = vscode.workspace.textDocuments.find(
    (d) => d.uri.toString() === entry.uri.toString(),
  );
  if (!doc) return false;
  const lineIdx = entry.line - 1;
  if (lineIdx < 0 || lineIdx >= doc.lineCount) return false;
  const text = doc.lineAt(lineIdx).text;
  return /\[tool:\s*[A-Za-z0-9_-]+/.test(text);
}

/**
 * Phase 3 step-control dispatch. Routes Step Into / Over / Out to one of
 * three behaviours depending on current state:
 *
 *  1. Run is step-paused (`step:awaiting` already received) → POST the
 *     new mode to the server's run-control endpoint. The SSE stream
 *     continues emitting events from the server's resumed step loop.
 *  2. Run is breakpoint-paused (the extension trimmed its step list at
 *     a breakpoint) → launch a fresh run from the pause line with the
 *     requested stepMode. Step Into starts a stepping session; Step
 *     Over / Out from a breakpoint pause behave the same way (they're
 *     all "advance one step from here under stepMode X").
 *  3. Otherwise (idle) → Step Into starts a fresh run from cursor/
 *     selection with stepMode='into'. Step Over / Out from idle are
 *     surface-only no-ops: there's no "current frame" to step over
 *     or out of yet.
 *
 * Toolbar-vs-keybinding asymmetry (Option D follow-up): the F11
 * keybinding deliberately fires from IDLE too (case 3 above), but the
 * StepInto toolbar button is hidden in IDLE — a StepInto glyph there
 * would imply "advance into the next call" when nothing is running,
 * which is misleading. The keybind preserves the power-user shortcut
 * "F11 starts a stepping run from cursor."
 */
async function dispatchStep(
  mode: StepMode,
  registry: Registry,
  tracker: ActiveFileTracker,
): Promise<void> {
  // Prefer the running controller over the active-editor controller
  // when a run is in flight. Without this, if the user has clicked
  // onto a side-by-side skill file (auto-revealed when the run paused
  // inside the skill), `registry.active()` returns the SKILL file's
  // controller — which has never run — so Step Over / Step Into try
  // to launch a NEW run on the skill file instead of advancing the
  // already-running outer test. When no run is in flight, fall back
  // to the active-editor controller so the "from idle" path (F11
  // starts a fresh stepping run) keeps working.
  const controller = registry.runningController() ?? registry.active();
  const editor = tracker.activeEditor;
  if (!controller || !editor) return notifyNoActive();

  // (1) Already step-paused — fast path: just deliver the next mode.
  // Phase 3.1.b: only POST when there's an actual paused step. A run
  // that's running-but-not-step-paused would otherwise generate a 409
  // and an ugly status-bar warning.
  if (controller.isRunning) {
    if (!registry.isStepPaused(controller.document.uri)) {
      vscode.window.setStatusBarMessage(
        'TestBench: run is in flight, not paused — press F5 to pause first',
        2500,
      );
      return;
    }
    // Phase 3.1.d: Step Out at depth 0 (test frame) is functionally
    // identical to Continue — the server's `'out'` decision never pauses
    // when there's no shallower frame to return to. Send `'continue'`
    // for cleaner intent and tell the user why.
    if (mode === 'out' && controller.frameStack.length === 0) {
      vscode.window.setStatusBarMessage(
        'TestBench: Step Out at the test frame = Continue',
        2000,
      );
      await controller.sendRunControl('continue');
      return;
    }
    // Phase 5 — Step Into on a `[tool: ...]` line asks the server to
    // pause at the tool dispatcher so VS Code's Node debugger can
    // attach. Detected by reading the line text at the parked
    // step-pause position; falls back to normal `into` otherwise.
    if (mode === 'into' && isAtToolLine(registry, controller)) {
      await controller.sendRunControl('into', { pauseAtNextTool: true });
      return;
    }
    await controller.sendRunControl(mode);
    return;
  }

  // (2) Breakpoint-paused: relaunch from that line with the chosen mode.
  // Anchor-derived current line — see continueRun above.
  const startLine = tracker.breakpointStopFor(controller.document.uri);
  const sectionCtx = tracker.resumeContextFor(controller.document.uri);
  if (startLine != null) {
    tracker.setBreakpointStop(controller.document.uri, null);
    const breakpoints = tracker.breakpoints(controller.document.uri);
    // Same section-body branch as `continueRun` — this is the second consumer
    // of the resume marker, and the one that gets forgotten.
    if (sectionCtx) {
      const plan = sectionResumePlan(
        editor.document.getText(),
        startLine,
        sectionCtx.callLine,
        controller.document.uri.fsPath,
      );
      if (!plan) {
        refuseStaleResume(tracker, controller.document.uri);
        return;
      }
      registry.notifyRunning(true);
      await controller
        .runLines(plan.lines, {
          breakpoints,
          skipBreakpointAtStart: true,
          isContinuation: true,
          stepMode: mode,
          ...(plan.rerun && { rerun: plan.rerun }),
        })
        .finally(() => registry.notifyRunning(false));
      return;
    }
    const resumeLines = extractSteps(editor.document.getText())
      .map((s) => s.line)
      .filter((line) => line >= startLine);
    if (resumeLines.length === 0) {
      refuseStaleResume(tracker, controller.document.uri);
      return;
    }
    // Phase 5 — if the breakpoint sat on a `[tool: ...]` line and the
    // command is Step Into, seed the run with `pauseAtNextTool: true`
    // so the server emits `tool:awaiting-debugger` before that step.
    const lineText = editor.document.lineAt(Math.max(0, startLine - 1)).text;
    const isToolLine = /\[tool:\s*[A-Za-z0-9_-]+/.test(lineText);
    const pauseAtNextTool = mode === 'into' && isToolLine;
    registry.notifyRunning(true);
    await controller
      .runLines(resumeLines, {
        breakpoints,
        skipBreakpointAtStart: true,
        stepMode: mode,
        // Resuming from a breakpoint pause is a continuation (same as
        // Continue) — without this, runLines clears all statuses and the
        // pass marks earned by steps before the breakpoint disappear when
        // the user Steps Into the next step.
        isContinuation: true,
        ...(pauseAtNextTool && { pauseAtNextTool: true }),
      })
      .finally(() => registry.notifyRunning(false));
    return;
  }

  // (3) Idle: only Step Into has meaning; Step Over / Out need a frame
  // to operate against and the user hasn't started one yet.
  if (mode !== 'into') {
    vscode.window.setStatusBarMessage(
      'TestBench: start a run (F5 or F11) before using Step Over / Step Out',
      2500,
    );
    return;
  }
  const lines = selectionLines(editor);
  const breakpoints = tracker.breakpoints(controller.document.uri);
  registry.notifyRunning(true);
  await controller
    .runLines(lines, { breakpoints, stepMode: 'into' })
    .finally(() => registry.notifyRunning(false));
}

/**
 * Refuse to resume from a pause marker that no longer names a runnable step.
 *
 * Both call sites have already cleared the marker by the time they get here —
 * they clear it before computing `resumeLines`, so a refused resume does not
 * leave the arrow painted. The clear below is belt-and-braces for a future
 * caller that doesn't.
 *
 * Both resume paths compute `resumeLines` as "every main-flow step at or
 * after the parked line". For a marker parked on a SECTION BODY line that
 * list is empty — bodies are defined below the main flow, so no main-flow
 * step sits at or after them — and passing `[]` to `runLines` is the literal
 * "run everything" convention. The run-line guard cannot help here: it fires
 * on a non-empty request that resolves to nothing, and this request is empty
 * to begin with, indistinguishable from batch mode.
 *
 * Body-line markers became possible the moment breakpoints inside sections
 * started pausing server-side. Nothing clears a marker except Stop, a new
 * run, or the next `step:start`, so a dropped stream or a restarted server
 * leaves one behind — and resuming from it would silently re-run the whole
 * test against a live session.
 */
/**
 * How to resume a marker parked inside a section body, or null when it can't
 * be resumed from where it sits.
 *
 * Two shapes, decided by whether an invocation was recorded with the marker:
 *
 *  - **Anchored** (`callLine` set) — the body was running under a call. Send
 *    that call line *and every main-flow step after it*, with `startAt` on
 *    the body line. The server expands the invocation into the whole body,
 *    anchors at the failed step, and runs on into the rest of the test — so
 *    Continue means the same thing here as it does in the main flow. Sending
 *    the whole tail rather than the invocation alone is also what
 *    disambiguates a section invoked twice: the first exact match inside an
 *    expansion that STARTS at this call can only be this invocation's.
 *  - **Detached** (`callLine` null) — nothing invoked the body; it was run
 *    directly from a selection. Re-run the rest of that section's body the
 *    same way, with no anchor. `runLines` re-derives section-body scope from
 *    the lines themselves.
 *
 * Null when the file has changed out from under the marker — no main-flow
 * step at the call line, or no body step left at the anchor.
 */
function sectionResumePlan(
  text: string,
  bodyLine: number,
  callLine: number | null,
  testFilePath: string,
): { lines: number[]; rerun?: { startAt: { uri: string; line: number } } } | null {
  if (callLine == null) {
    const lines = sectionBodyLinesAt(text, bodyLine).filter((line) => line >= bodyLine);
    return lines.length > 0 ? { lines } : null;
  }
  const lines = extractSteps(text)
    .map((s) => s.line)
    .filter((line) => line >= callLine);
  if (lines.length === 0) return null;
  return { lines, rerun: { startAt: { uri: testFilePath, line: bodyLine } } };
}

function refuseStaleResume(tracker: ActiveFileTracker, uri: vscode.Uri): void {
  tracker.setBreakpointStop(uri, null);
  vscode.window.setStatusBarMessage(
    'TestBench: the paused step is no longer runnable on its own — use Run All',
    4000,
  );
}

/**
 * Reveal the compile's recording — the DOM either side of every step, the
 * candidate, any replay failure — in the Explorer
 * (stories/codebehind-recording-on-disk.md §What the author sees). The
 * directory may not exist when a compile failed before it recorded; say so
 * rather than reveal nothing.
 */
async function revealRecording(dir: string): Promise<void> {
  if (!fs.existsSync(dir)) {
    vscode.window.showInformationMessage(`No recording at ${dir} — the compile did not get as far as recording.`);
    return;
  }
  await vscode.commands.executeCommand('revealInExplorer', vscode.Uri.file(dir));
}

/**
 * The sentence a partial compile adds to its notification: where the run
 * stopped, what was written off, what is unproven. Each part only when it
 * applies, so a plain prefix compile reads as one short instruction.
 */
export function partialNotes(summary: {
  stoppedAt?: { step: number; error: string };
  notAttempted: number[];
  writtenOffAi: number[];
  unproven: number[];
}): string {
  const parts: string[] = [];
  if (summary.stoppedAt) {
    parts.push(
      ` Step ${summary.stoppedAt.step} failed under AI — ${summary.stoppedAt.error}.` +
        (summary.notAttempted.length > 0 ? ` ${listSteps(summary.notAttempted)} not attempted.` : '') +
        ' Fix it, run, and compile again for the rest.',
    );
  }
  if (summary.writtenOffAi.length > 0) {
    parts.push(
      ` ${listSteps(summary.writtenOffAi)} kept AI after replay failures — fix the cause, then Compile This Step.`,
    );
  }
  if (summary.unproven.length > 0) {
    parts.push(` ${listSteps(summary.unproven)} unproven — the next run proves or flags them.`);
  }
  return parts.join('');
}

/** "Steps 6–9", "Step 4", "Steps 2, 5". */
function listSteps(numbers: number[]): string {
  if (numbers.length === 1) return `Step ${numbers[0]}`;
  const sorted = [...numbers].sort((a, b) => a - b);
  const contiguous = sorted.every((n, i) => i === 0 || n === sorted[i - 1]! + 1);
  return contiguous
    ? `Steps ${sorted[0]}–${sorted[sorted.length - 1]}`
    : `Steps ${sorted.join(', ')}`;
}
